
#ifndef _COMPONENT_TYPES_H_
#define _COMPONENT_TYPES_H_

typedef enum {

	E_COMPONENT_TYPE_NONE = 0,
	E_COMPONENT_TYPE_RENDERER,
	E_COMPONENT_TYPE_TRANSFORM,
	E_COMPONENT_TYPE_INPUT_HANDLER,
	E_COMPONENT_TYPE_PHYSICS,
	E_COMPONENT_TYPE_BUTTONS,
	E_COMPONENT_TYPE_DEBUG_DRAW,
}ComponentType;

#endif // !_COMPONENT_TYPES_H_
